Festival/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
app = Flask(__name__)
app.config["SECRET_KEY"] = '24185145a2eeb15bdfd87216873761ba'



app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"


app.config["MAIL_SERVER"] = "smtp.yandex.ru"
app.config["MAIL_PORT"] = 587
app.config["MAIL_USE_TLS"] = True
app.config["MAIL_USERNAME"] = "pavel.mefokov@yandex.ru"
app.config["MAIL_DEFAULT_SENDER"] = "pavel.mefokov@yandex.ru"
app.config["MAIL_PASSWORD"] = "cuayaeqvihbahuky"
mail = Mail(app)
db = SQLAlchemy(app)
login_manager = LoginManager(app)
bc = Bcrypt(app)



from Festival.users.routes import users_bl
from Festival.posts.routes import posts_bl
from Festival.main.routes import main_bl

app.register_blueprint(users_bl)
app.register_blueprint(posts_bl)
app.register_blueprint(main_bl)

Festival/main/routes.py
from flask import Blueprint
from flask import render_template, request
from Festival.database.model import Festival
main_bl = Blueprint("main_bl", __name__)


@main_bl.route("/", methods=["GET"])
@main_bl.route("/home")
def home():
    args = request.args.get("page", 1, int)
    result = Festival.query.paginate(per_page=5, page=args)
    return render_template("home.html", queries=result, title="Festivals", a=True)

Festival/posts/routes.py
from flask import Blueprint
from flask_login import login_required, current_user
from flask import request, flash, render_template, redirect, url_for
from Festival.database.model import Festival
from Festival.posts.form import AddFestival
from Festival import db

posts_bl = Blueprint("posts_bl", __name__)


@login_required
@posts_bl.route("/add", methods=["GET", "POST"])
def add():
    form_obj = AddFestival()
    flag = "Добавление информации о фестивале"
    if (request.method == "POST"):
        result = form_obj.validate()
        if result:
            if (form_obj.end.data < form_obj.start.data):
                flash("Введите корректные даты! Конец не может быть позже начала")
                return render_template("add.html", flag=flag, form=form_obj)
            new_record = Festival(name=form_obj.name.data,
                                  country=form_obj.country.data, city=form_obj.city.data,
                                  start=form_obj.start.data, end=form_obj.end.data, author=current_user.id)
            db.session.add(new_record)
            db.session.commit()
            flash('Информация успешно добавлена!')
            form_obj.clear()
    return render_template("add.html", flag=flag, title="Add new festival", form=form_obj)


@login_required
@posts_bl.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    form_obj = AddFestival()
    if (request.method == "GET"):
        fest_obj = db.session.get(Festival, int(id))
        form_obj.fill(fest_obj)
        return render_template("add.html", flag="Редактирование", title="Update Festval", form=form_obj)
    fest_obj = Festival.query.get(int(id))
    fest_obj.name = form_obj.name.data
    fest_obj.country = form_obj.country.data
    fest_obj.city = form_obj.city.data
    fest_obj.start = form_obj.start.data
    fest_obj.end = form_obj.end.data
    db.session.commit()
    flash("Успешно!")
    return render_template("add.html", flag="Редактирование", title="Update Festival", form=form_obj)


@login_required
@posts_bl.route("/delete/<int:id>", methods=["GET"])
def delete(id):
    fest_obj = Festival.query.get(int(id))
    db.session.delete(fest_obj)
    db.session.commit()
    return redirect(url_for("users_bl.account"))

Festival/users/routes.py
from flask import Blueprint
from flask_login import current_user, login_required, login_user, logout_user
from Festival.users.form import RegistrationForm, LoginForm, UpdateAccountForm, SendRequestForm, ResetPasswordForm
from flask import redirect, flash, url_for, render_template, request
from Festival import db, bc
from Festival.database.model import User, Festival
from Festival.main.utils import send_mail, save_picture

users_bl = Blueprint("users_bl", __name__)


@users_bl.route("/register", methods=["POST", "GET"])
def register():
    if (current_user.is_authenticated):
        return redirect(url_for("main_bl.home"))
    reg_form = RegistrationForm()
    if (reg_form.validate_on_submit()):
        hashed_password = bc.generate_password_hash(
            reg_form.password.data).decode("utf-8")
        user = User(username=reg_form.username.data,
                    email=reg_form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Зарегистрирован новый пользователь {reg_form.username.data}")
        return redirect(url_for('users_bl.login'))
    return render_template("register.html", title="Sing Up", form=reg_form)


@users_bl.route("/login", methods=["POST", "GET"])
def login():
    if (current_user.is_authenticated):
        return redirect(url_for("main_bl.home"))
    login_form = LoginForm()
    if (login_form.validate_on_submit()):
        # with Session() as session:
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and bc.check_password_hash(user.password, login_form.password.data):
            flash(f"Вы успешно вошли!", "succes")
            login_user(user)
            return redirect(url_for("main_bl.home"))
        else:
            flash("Проверьте правильность введенных данных", "danger")
    return render_template("login.html", title="Sing Up", form=login_form)


@users_bl.route("/logout")
def logout():
    logout_user()
    flash("Вы успешно вышли")
    return redirect(url_for("main_bl.home"))


@users_bl.route("/my_account", methods=["GET", "POST"])
@login_required
def account():
    UpdateForm = UpdateAccountForm()
    if (UpdateForm.validate_on_submit()):
        user = User.query.get(current_user.id)
        user.username = UpdateForm.username.data
        current_user.username = user.username
        user.email = UpdateForm.email.data
        current_user.email = user.email
        if (UpdateForm.picture.data):
            user.image = save_picture(UpdateForm.picture.data)
            current_user.image = user.image
        db.session.commit()
        flash("Ваша данные успешно обновлены!")
    elif (request.method == "GET"):
        UpdateForm.username.data = current_user.username
        UpdateForm.email.data = current_user.email
    image_jpg = url_for(
        "static", filename="image_profile/" + current_user.image)
    argv = request.args.get("page", 1, int)
    res = Festival.query.filter(
        Festival.author_id == current_user.id).paginate(per_page=5, page=argv)
    return render_template("account.html", title="Account", image=image_jpg, form=UpdateForm, queries=res)


@users_bl.route('/account/<int:id>')
def user_account(id):
    user = User.query.get(id)
    p = url_for("static", filename="image_profile/"+user.image)
    argv = request.args.get("page", 1, int)
    result = Festival.query.filter(
        Festival.author_id == id).paginate(per_page=5, page=argv)
    return render_template("user_account.html", title="Info", path=p, user=user, queries=result)


@users_bl.route("/send_request", methods=["GET", "POST"])
def send_request():
    if (current_user.is_authenticated):
        return redirect("home")
    form = SendRequestForm()
    if (form.validate_on_submit()):
        user = User.query.filter(User.email == form.email.data).first()
        flash("Дальнейшая инструкция выслана на почту")
        send_mail(user)
    return render_template("send_request.html", form=form)


@users_bl.route("/reset_password/<string:token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect("home")
    form = ResetPasswordForm()
    if (form.validate_on_submit()):
        user = User.verify_token(token)
        if (user is None):
            flash("Истекшая или недействительная ссылка")
            return redirect(url_for("users_bl.send_request"))
        user.password = bc.generate_password_hash(form.password.data)
        db.session.commit()
        flash("Пароль успешно изменен!")
        return redirect(url_for("users_bl.login"))
    return render_template("reset_password.html", form=form)

Festival/templates/account.html
{% extends "user_account.html"%}

{%block content%}
<p>Добро пожаловать, {{current_user.username}}!</p>
<figcaption>
    <img src="{{image}}" alt="Фото профиля" height="128" width="128" />
    <br />
    <caption>Фото профиля</caption>
</figcaption>
<form action="" method="post" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <fieldset>
        <legend>Сведения</legend>
        <p>{{form.username.label()}}</p>
        <p>{{form.username()}}</p>
        {% if form.username.errors %}
        {% for error in form.username.errors%}
        <p>{{error}}</p>
        {%endfor%}
        {% endif %}

        <p>{{form.email.label()}}</p>
        <p>{{form.email()}}</p>
        {% if form.email.errors %}
        {% for error in form.email.errors%}
        <p>{{error}}</p>
        {%endfor%}
        {% endif %}

        <p>{{form.picture.label()}}</p>
        <p>{{form.picture()}}</p>

        {% if form.picture.errors %}
        {% for error in form.picture.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}

        <p>{{form.submit()}}</p>
    </fieldset>
</form>


{% for query in queries.items %}
<h3>{{query.name}}</h3>
<p>{{query.country}}, {{query.city}}</p>
<p><b>Начало</b>:{{query.start.strftime("%d.%m.%Y")}} <br />
    <b>Конец</b>:{{query.end.strftime("%d.%m.%Y")}}
</p>
{% if current_user.id == query.author_id %}
<a href="{{url_for('posts_bl.update', id = query.id)}}">Изменить</a>
<a href="{{url_for('posts_bl.delete', id = query.id)}}">Удалить</a>
{% endif %}
<hr />
{% endfor %}



{% for query in queries.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 1) %}
{% if query %}
    {% if query == queries.page%}
        <a href="{{url_for('users_bl.account', page = query)}}"><b>{{query}}</b></a>
    {% else %}
        <a href="{{url_for('users_bl.account', page = query)}}">{{query}}</a>
    {% endif %}
{% else %}
...
{% endif %}
{% endfor %}

{%endblock content%}

Festival/templates/add.html
{% extends "layout.html"%}
{% block content %}
<form method="post">
    {{form.hidden_tag()}}
    <fieldset>
        <legend>{{flag}}</legend>
        <p>{{form.name.label}}: {{form.name()}}</p>
        {% if form.name.errors %}
        {% for error in form.name.errors%}
        <p>error</p>
        {% endfor %}
        {% endif %}


        <p>{{form.country.label}}: {{form.country()}}</p>

        {% if form.country.errors %}
        {% for error in form.country.errors%}
        <p>error</p>
        {% endfor %}
        {% endif %}


        <p>{{form.city.label}}: {{form.city()}}</p>

        {% if form.city.errors %}
        {% for error in form.city.errors%}
        <p>error</p>
        {% endfor %}
        {% endif %}


        <p>{{form.start.label}}: {{form.start()}}</p>

        {% if form.start.errors %}
        {% for error in form.start.errors%}
        <p>error</p>
        {% endfor %}
        {% endif %}

        <p>{{form.end.label}}: {{form.end()}}</p>

        {% if form.end.errors %}
        {% for error in form.end.errors%}
        <p>error</p>
        {% endfor %}
        {% endif %}
        <p>{{form.submit()}}</p>
    </fieldset>
</form>
{% endblock content %}

Festival/templates/home.html
{% extends "layout.html" %}
{% block content %}


{% if current_user.is_authenticated%}
<p>Добро пожаловать, {{current_user.username}}</p>
<a href="{{url_for('posts_bl.add')}}">Добавить информацию+</a>
<a href="{{url_for('users_bl.account')}}">Мой аккаунт</a>
<a href="{{url_for('users_bl.logout')}}">Выйти</a>
{% else %}
<a href="{{url_for('users_bl.register')}}">Регистрация</a>
<a href="{{url_for('users_bl.login')}}">Войти</a>
{% endif %}


{% if queries %}
{% for query in queries.items %}
<h2>{{query.author.username}}</h2>
<p>{{query.country}}, {{query.city}}</p>
<p><b>Начало</b>:{{query.start.strftime("%d.%m.%Y")}} <br />
    <b>Конец</b>:{{query.end.strftime("%d.%m.%Y")}}
<p>Создано: <a href="{{url_for('users_bl.user_account', id = query.author_id)}}">{{query.author.username}}</a></p>
</p>
<hr />
{% endfor %}

{% endif %}


{% for query in queries.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 1) %}
{% if query %}
{% if query == queries.page%}
<a href="{{url_for('main_bl.home', page = query)}}" color=""><b>{{query}}</b></a>
{% else %}
<a href="{{url_for('main_bl.home', page = query)}}">{{query}}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}

{%endblock content%}

Festival/templates/layout.html
<html>

<head>
    <title>{{title}}</title>
</head>

<body>
    {% if not a %}
    <a href="{{url_for('main_bl.home')}}">На главную</a>
    {% endif %}
    {% with messages = get_flashed_messages()%}
    {% if messages %}
    <br />
    {% for message in messages%}
    {{message}}
    {% endfor %}
    <br />
    {% endif %}
    {% endwith %}
    {%block content%}{%endblock content%}
</body>

</html>

Festival/templates/login.html
{% extends "layout.html"%}

{% block content%}
<form method="POST">
    {{form.hidden_tag()}}
    <fieldset>
        <legend>Войти</legend>
        <p>{{form.email.label()}}: {{form.email()}}</p>
        {% if form.email.errors %}
        {% for error in form.email.errors%}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        <p>{{form.password.label()}}: {{form.password()}}</p>
        {% if form.password.errors %}
        {% for error in form.password.errors%}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        <p>{{form.remember.label()}}: {{form.remember()}}</p>
        {{form.submit()}}
        <br />
        <div>
            <a href = "{{url_for('users_bl.send_request')}}"><small>Забыли пароль?</small></a>
        </div>
        <div>
            <a href="{{url_for('users_bl.register')}}"><small>Регистрация</small></a>
        </div>
    </fieldset>
</form>
{% endblock content%}

Festival/templates/register.html
{% extends "layout.html" %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
    <fieldset>
        <legend>Регистрация</legend>
        <p>{{ form.user_name.label }}: {{ form.user_name() }}</p>
        {% if form.user_name.errors %}
        {% for error in form.user_name.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        <p>{{ form.email.label }}: {{ form.email() }}</p>
        {% if form.email.errors %}
        {% for error in form.email.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}


        <p>{{ form.password.label }}: {{ form.password() }}</p>
        {% if form.password.errors %}
        {% for error in form.password.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}


        <p>{{ form.confirm_password.label }}: {{ form.confirm_password() }}</p>
        {% if form.confirm_password.errors %}
        {% for error in form.confirm_password.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        {{ form.submit() }}
        <br />
        <small>Уже есть аккаунт?<a href="{{url_for('login')}}">Войти</a></small>
    </fieldset>
</form>
<a href="{{url_for('home')}}">На Главную</a>
{% endblock content %}

Festival/templates/reset_password.html
{% extends "layout.html" %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
    <fieldset>
        <legend>Восстановление пароля</legend>

        <p>{{ form.password.label }}: {{ form.password() }}</p>
        {% if form.password.errors %}
        {% for error in form.password.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}


        <p>{{ form.confirm_password.label }}: {{ form.confirm_password() }}</p>
        {% if form.confirm_password.errors %}
        {% for error in form.confirm_password.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        {{ form.submit() }}
        <br />
    </fieldset>
</form>
{% endblock content %}

Festival/templates/send_request.html
{% extends "layout.html"%}

{% block content%}
<form method="POST">
    {{form.hidden_tag()}}
    <fieldset>
        <legend>Восстановление по почте</legend>
        <p>{{form.email.label()}}: {{form.email()}}</p>
        {% if form.email.errors %}
        {% for error in form.email.errors%}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        {{form.submit()}}
        <br />
    </fieldset>
</form>
{% endblock content%}

Festival/templates/update.html
{% extends "layout.html"%}
{% block content%}
<form method="POST" action="{{url_for('posts_bl.update')}}">
    <fieldset>
        <legend>Редактирование</legend>
        <p>Введите новое название фестиваля: <input name="name" required="required" value="{{memory.name}}" /></p>
        <p>Введите новою страну: <input name="country" required="required" value="{{memory.country}}" /></p>
        <p>Введите новый город: <input name="city" required="required" value="{{memory.city}}" /></p>
        <p>Введите новую дату начала фестиваля: <input name="start" type="date"
                value="{{ memory.start.strftime('%Y-%m-%d') }}" required="required" /></p>
        <p>Введите новую дату конца фестиваля: <input name="end" type="date"
                value="{{ memory.end.strftime('%Y-%m-%d') }}" required="required" /></p>
        <input type="submit" value="Изменить" />
    </fieldset>
</form>
{% endblock content %}

Festival/templates/user_account.html
{% extends "layout.html" %}
{% block content %}
<p>Пользователь: {{user.username}}</p>
<p>Сведения: </p>

<div>
    <img src="{{path}}" alt="Фото профиля" height="120" weight="160" />
</div>
<div>
    <p>Почта: <a href="mailto:{{user.email}}">{{user.email}}</a></p>
</div>


<h1>Посты Пользователя</h1>
{% for query in queries.items %}
<h3>{{query.name}}</h3>
<p>{{query.country}}, {{query.city}}</p>
<p><b>Начало</b>:{{query.start.strftime("%d.%m.%Y")}} <br />
    <b>Конец</b>:{{query.end.strftime("%d.%m.%Y")}}
</p>
<hr />
{% endfor %}



{% for query in queries.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 1) %}
{% if query %}
{% if query == queries.page%}
<a href="{{url_for('users_bl.user_account', id = user.id, page = query)}}"><b>{{query}}</b></a>
{% else %}
<a href="{{url_for('users_bl.user_account', id = user.id, page = query)}}">{{query}}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}

{% endblock content %}